### ISSUE TITLE
공통응답과 익셉션처리 구현

### ISSUE THREAD

**Issue by Revi1337** [apartribe/apartribe-backend#6]
- [x] Global Exception 처리
- [ ] 공통 Response 처리

**Comment by HWAHAEBANG** [comment]
수고가 많으십니다. 질문 있습니다.
작업할 목록을 이슈로 관리하시는 목적은 잘 알겠습니다.
그러나 해당 내용들은 커밋 메시지들에 다 기록이 남는 내용들이기도 할텐데, 이런 방식으로 이슈에도 남기면 어떤 점이 좋은가요?

**Comment by Revi1337** [comment]
그냥요. 실무에서의 흐름을 따라해보고싶었는데, 이것땜에 속도가 안나서 걍 떄려칠라구요 다 닫습니다
